config/routes.rb
Rails.application.routes.draw do



  resources :pinpin_pin_worshops
  resources :pinpin_pin_worshopsses
  resources :notes
resources :user
  resources :handbooks
  resources :worships do
    resources :pin_worships
  end
root to: 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pinpin_pin_worshop.rb
class PinpinPinWorshop < ApplicationRecord
end

app/models/pinpin_pin_worshopss.rb
class PinpinPinWorshopss < ApplicationRecord
end

app/controllers/pinpin_pin_worshops_controller.rb
class PinpinPinWorshopsController < ApplicationController
  before_action :set_pinpin_pin_worshop, only: [:show, :edit, :update, :destroy]

  # GET /pinpin_pin_worshops
  # GET /pinpin_pin_worshops.json
  def index
    @pinpin_pin_worshops = PinpinPinWorshop.all
  end

  # GET /pinpin_pin_worshops/1
  # GET /pinpin_pin_worshops/1.json
  def show
  end

  # GET /pinpin_pin_worshops/new
  def new
    @pinpin_pin_worshop = PinpinPinWorshop.new
  end

  # GET /pinpin_pin_worshops/1/edit
  def edit
  end

  # POST /pinpin_pin_worshops
  # POST /pinpin_pin_worshops.json
  def create
    @pinpin_pin_worshop = PinpinPinWorshop.new(pinpin_pin_worshop_params)

    respond_to do |format|
      if @pinpin_pin_worshop.save
        format.html { redirect_to @pinpin_pin_worshop, notice: 'Pinpin pin worshop was successfully created.' }
        format.json { render :show, status: :created, location: @pinpin_pin_worshop }
      else
        format.html { render :new }
        format.json { render json: @pinpin_pin_worshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pinpin_pin_worshops/1
  # PATCH/PUT /pinpin_pin_worshops/1.json
  def update
    respond_to do |format|
      if @pinpin_pin_worshop.update(pinpin_pin_worshop_params)
        format.html { redirect_to @pinpin_pin_worshop, notice: 'Pinpin pin worshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @pinpin_pin_worshop }
      else
        format.html { render :edit }
        format.json { render json: @pinpin_pin_worshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pinpin_pin_worshops/1
  # DELETE /pinpin_pin_worshops/1.json
  def destroy
    @pinpin_pin_worshop.destroy
    respond_to do |format|
      format.html { redirect_to pinpin_pin_worshops_url, notice: 'Pinpin pin worshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pinpin_pin_worshop
      @pinpin_pin_worshop = PinpinPinWorshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pinpin_pin_worshop_params
      params.require(:pinpin_pin_worshop).permit(:text)
    end
end

app/helpers/pinpin_pin_worshops_helper.rb
module PinpinPinWorshopsHelper
end

app/views/pinpin_pin_worshops/_form.html.erb
<%= form_with(model: pinpin_pin_worshop, local: true) do |form| %>
  <% if pinpin_pin_worshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pinpin_pin_worshop.errors.count, "error") %> prohibited this pinpin_pin_worshop from being saved:</h2>

      <ul>
      <% pinpin_pin_worshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :pinpin_pin_worshop_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pinpin_pin_worshops/edit.html.erb
<h1>Editing Pinpin Pin Worshop</h1>

<%= render 'form', pinpin_pin_worshop: @pinpin_pin_worshop %>

<%= link_to 'Show', @pinpin_pin_worshop %> |
<%= link_to 'Back', pinpin_pin_worshops_path %>

app/views/pinpin_pin_worshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pinpin Pin Worshops</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pinpin_pin_worshops.each do |pinpin_pin_worshop| %>
      <tr>
        <td><%= pinpin_pin_worshop.text %></td>
        <td><%= link_to 'Show', pinpin_pin_worshop %></td>
        <td><%= link_to 'Edit', edit_pinpin_pin_worshop_path(pinpin_pin_worshop) %></td>
        <td><%= link_to 'Destroy', pinpin_pin_worshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pinpin Pin Worshop', new_pinpin_pin_worshop_path %>

app/views/pinpin_pin_worshops/new.html.erb
<h1>New Pinpin Pin Worshop</h1>

<%= render 'form', pinpin_pin_worshop: @pinpin_pin_worshop %>

<%= link_to 'Back', pinpin_pin_worshops_path %>

app/views/pinpin_pin_worshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @pinpin_pin_worshop.text %>
</p>

<%= link_to 'Edit', edit_pinpin_pin_worshop_path(@pinpin_pin_worshop) %> |
<%= link_to 'Back', pinpin_pin_worshops_path %>