config/routes.rb
Rails.application.routes.draw do



  resources :pinpin_pin_worshops
  resources :pinpin_pin_worshopsses
  resources :notes
resources :user
  resources :handbooks
  resources :worships do
    resources :pin_worships
  end
root to: 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/handbook.rb
class Handbook < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/pin_worship.rb
class PinWorship < ApplicationRecord

  belongs_to :worship

end

app/models/pinpin_pin_worshop.rb
class PinpinPinWorshop < ApplicationRecord
end

app/models/pinpin_pin_worshopss.rb
class PinpinPinWorshopss < ApplicationRecord
end

app/models/sickness.rb
class Sickness < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worship.rb
class Worship < ApplicationRecord

  has_many :pin_worship, :dependent => :destroy

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text)
    end
end

app/controllers/pinpin_pin_worshopsses_controller.rb
class PinpinPinWorshopssesController < ApplicationController
  before_action :set_pinpin_pin_worshopss, only: [:show, :edit, :update, :destroy]

  # GET /pinpin_pin_worshopsses
  # GET /pinpin_pin_worshopsses.json
  def index
    @pinpin_pin_worshopsses = PinpinPinWorshopss.all
  end

  # GET /pinpin_pin_worshopsses/1
  # GET /pinpin_pin_worshopsses/1.json
  def show
  end

  # GET /pinpin_pin_worshopsses/new
  def new
    @pinpin_pin_worshopss = PinpinPinWorshopss.new
  end

  # GET /pinpin_pin_worshopsses/1/edit
  def edit
  end

  # POST /pinpin_pin_worshopsses
  # POST /pinpin_pin_worshopsses.json
  def create
    @pinpin_pin_worshopss = PinpinPinWorshopss.new(pinpin_pin_worshopss_params)

    respond_to do |format|
      if @pinpin_pin_worshopss.save
        format.html { redirect_to @pinpin_pin_worshopss, notice: 'Pinpin pin worshopss was successfully created.' }
        format.json { render :show, status: :created, location: @pinpin_pin_worshopss }
      else
        format.html { render :new }
        format.json { render json: @pinpin_pin_worshopss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pinpin_pin_worshopsses/1
  # PATCH/PUT /pinpin_pin_worshopsses/1.json
  def update
    respond_to do |format|
      if @pinpin_pin_worshopss.update(pinpin_pin_worshopss_params)
        format.html { redirect_to @pinpin_pin_worshopss, notice: 'Pinpin pin worshopss was successfully updated.' }
        format.json { render :show, status: :ok, location: @pinpin_pin_worshopss }
      else
        format.html { render :edit }
        format.json { render json: @pinpin_pin_worshopss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pinpin_pin_worshopsses/1
  # DELETE /pinpin_pin_worshopsses/1.json
  def destroy
    @pinpin_pin_worshopss.destroy
    respond_to do |format|
      format.html { redirect_to pinpin_pin_worshopsses_url, notice: 'Pinpin pin worshopss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pinpin_pin_worshopss
      @pinpin_pin_worshopss = PinpinPinWorshopss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pinpin_pin_worshopss_params
      params.require(:pinpin_pin_worshopss).permit(:text)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all

  end

  def show
     @user = User.find(params[:id])
  end
end

app/controllers/worships_controller.rb
class WorshipsController < ApplicationController
  before_action :set_worship, only: [:show, :edit, :update, :destroy]

  # GET /worships
  # GET /worships.json
  def index
    @worships = Worship.all
  end

  # GET /worships/1
  # GET /worships/1.json
  def show
    @worships = Worship.find(params[:id])

    @pin_worship = PinWorship.new

  end

  # GET /worships/new
  def new
    @worship = Worship.new
  end

  # GET /worships/1/edit
  def edit
  end

  # POST /worships
  # POST /worships.json
  def create
    @worship = Worship.new(worship_params)

    respond_to do |format|
      if @worship.save
        format.html { redirect_to @worship, notice: 'Worship was successfully created.' }
        format.json { render :show, status: :created, location: @worship }
      else
        format.html { render :new }
        format.json { render json: @worship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worships/1
  # PATCH/PUT /worships/1.json
  def update
    respond_to do |format|
      if @worship.update(worship_params)
        format.html { redirect_to @worship, notice: 'Worship was successfully updated.' }
        format.json { render :show, status: :ok, location: @worship }
      else
        format.html { render :edit }
        format.json { render json: @worship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worships/1
  # DELETE /worships/1.json
  def destroy
    @worship.destroy
    respond_to do |format|
      format.html { redirect_to worships_url, notice: 'Worship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worship
      @worship = Worship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worship_params
      params.require(:worship).permit(:days)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/handbooks_helper.rb
module HandbooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pin_worships_helper.rb
module PinWorshipsHelper
end

app/helpers/pinpin_pin_worshopsses_helper.rb
module PinpinPinWorshopssesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/worships_helper.rb
module WorshipsHelper
end

app/views/pinpin_pin_worshopsses/_form.html.erb
<%= form_with(model: pinpin_pin_worshopss, local: true) do |form| %>
  <% if pinpin_pin_worshopss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pinpin_pin_worshopss.errors.count, "error") %> prohibited this pinpin_pin_worshopss from being saved:</h2>

      <ul>
      <% pinpin_pin_worshopss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :pinpin_pin_worshopss_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pinpin_pin_worshopsses/edit.html.erb
<h1>Editing Pinpin Pin Worshopss</h1>

<%= render 'form', pinpin_pin_worshopss: @pinpin_pin_worshopss %>

<%= link_to 'Show', @pinpin_pin_worshopss %> |
<%= link_to 'Back', pinpin_pin_worshopsses_path %>

app/views/pinpin_pin_worshopsses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pinpin Pin Worshopsses</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pinpin_pin_worshopsses.each do |pinpin_pin_worshopss| %>
      <tr>
        <td><%= pinpin_pin_worshopss.text %></td>
        <td><%= link_to 'Show', pinpin_pin_worshopss %></td>
        <td><%= link_to 'Edit', edit_pinpin_pin_worshopss_path(pinpin_pin_worshopss) %></td>
        <td><%= link_to 'Destroy', pinpin_pin_worshopss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pinpin Pin Worshopss', new_pinpin_pin_worshopss_path %>

app/views/pinpin_pin_worshopsses/new.html.erb
<h1>New Pinpin Pin Worshopss</h1>

<%= render 'form', pinpin_pin_worshopss: @pinpin_pin_worshopss %>

<%= link_to 'Back', pinpin_pin_worshopsses_path %>

app/views/pinpin_pin_worshopsses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @pinpin_pin_worshopss.text %>
</p>

<%= link_to 'Edit', edit_pinpin_pin_worshopss_path(@pinpin_pin_worshopss) %> |
<%= link_to 'Back', pinpin_pin_worshopsses_path %>