config/routes.rb
Rails.application.routes.draw do



  resources :pinpin_pin_worshops
  resources :pinpin_pin_worshopsses
  resources :notes
resources :user
  resources :handbooks
  resources :worships do
    resources :pin_worships
  end
root to: 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pin_worship.rb
class PinWorship < ApplicationRecord

  belongs_to :worship

end

app/controllers/pin_worships_controller.rb
class PinWorshipsController < ApplicationController
  before_action :set_pin_worship, only: [:show, :edit, :update, :destroy]

  # worship /pin_worships
  # worship /pin_worships.json
  def create


    @worship = Worship.find(params[:worship_id])
    @pin_worship = @worship.pin_worships.create(params[:comment].permit(:name, :comment))
    redirect_to worship_path(@worship)


    @pin_worship = PinWorship.new(pin_worship_params)

    respond_to do |format|
      if @pin_worship.save
        format.html { redirect_to @pin_worship, notice: 'Pin worship was successfully created.' }
        format.json { render :show, status: :created, location: @pin_worship }
      else
        format.html { render :new }
        format.json { render json: @pin_worship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pin_worships/1
  # PATCH/PUT /pin_worships/1.json


  # DELETE /pin_worships/1
  # DELETE /pin_worships/1.json
  def destroy
    @pin_worship.destroy
    respond_to do |format|
      format.html { redirect_to pin_worships_url, notice: 'Pin worship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin_worship
      @pin_worship = PinWorship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_worship_params
      params.require(:pin_worship).permit(:title, :lat, :lng, :img_url, :info_text)
    end
end

app/helpers/pin_worships_helper.rb
module PinWorshipsHelper
end

app/views/pin_worships/_form.html.erb
<%= form_with(model: pin_worship, local: true) do |form| %>
  <% if pin_worship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin_worship.errors.count, "error") %> prohibited this pin_worship from being saved:</h2>

      <ul>
      <% pin_worship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :pin_worship_title %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :pin_worship_lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng, id: :pin_worship_lng %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url, id: :pin_worship_img_url %>
  </div>

  <div class="field">
    <%= form.label :info_text %>
    <%= form.text_field :info_text, id: :pin_worship_info_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pin_worships/edit.html.erb
<h1>Editing Pin Worship</h1>

<%= render 'form', pin_worship: @pin_worship %>

<%= link_to 'Show', @pin_worship %> |
<%= link_to 'Back', pin_worships_path %>

app/views/pin_worships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pin Worships</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Img url</th>
      <th>Info text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pin_worships.each do |pin_worship| %>
      <tr>
        <td><%= pin_worship.title %></td>
        <td><%= pin_worship.lat %></td>
        <td><%= pin_worship.lng %></td>
        <td><%= pin_worship.img_url %></td>
        <td><%= pin_worship.info_text %></td>
        <td><%= link_to 'Show', pin_worship %></td>
        <td><%= link_to 'Edit', edit_pin_worship_path(pin_worship) %></td>
        <td><%= link_to 'Destroy', pin_worship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin Worship', new_pin_worship_path %>

app/views/pin_worships/new.html.erb
<h1>New Pin Worship</h1>

<%= render 'form', pin_worship: @pin_worship %>

<%= link_to 'Back', pin_worships_path %>

app/views/pin_worships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pin_worship.title %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @pin_worship.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @pin_worship.lng %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @pin_worship.img_url %>
</p>

<p>
  <strong>Info text:</strong>
  <%= @pin_worship.info_text %>
</p>

<%= @pin_worship.spots(-33.8670522, 151.1957362, :detail => true) %>

<%= link_to 'Edit', edit_pin_worship_path(@pin_worship) %> |
<%= link_to 'Back', pin_worships_path %>