config/routes.rb
Rails.application.routes.draw do



  resources :pinpin_pin_worshops
  resources :pinpin_pin_worshopsses
  resources :notes
resources :user
  resources :handbooks
  resources :worships do
    resources :pin_worships
  end
root to: 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/handbook.rb
class Handbook < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/pin_worship.rb
class PinWorship < ApplicationRecord

  belongs_to :worship

end

app/models/pinpin_pin_worshop.rb
class PinpinPinWorshop < ApplicationRecord
end

app/models/pinpin_pin_worshopss.rb
class PinpinPinWorshopss < ApplicationRecord
end

app/models/sickness.rb
class Sickness < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/worship.rb
class Worship < ApplicationRecord

  has_many :pin_worship, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/handbooks_controller.rb
class HandbooksController < ApplicationController
  before_action :set_handbook, only: [:show, :edit, :update, :destroy]

  # GET /handbooks
  # GET /handbooks.json
  def index
    @handbooks = Handbook.all
  end

  # GET /handbooks/1
  # GET /handbooks/1.json
  def show
  end

  # GET /handbooks/new
  def new
    @handbook = Handbook.new
  end

  # GET /handbooks/1/edit
  def edit
  end

  # POST /handbooks
  # POST /handbooks.json
  def create
    @handbook = Handbook.new(handbook_params)

    respond_to do |format|
      if @handbook.save
        format.html { redirect_to @handbook, notice: 'Handbook was successfully created.' }
        format.json { render :show, status: :created, location: @handbook }
      else
        format.html { render :new }
        format.json { render json: @handbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handbooks/1
  # PATCH/PUT /handbooks/1.json
  def update
    respond_to do |format|
      if @handbook.update(handbook_params)
        format.html { redirect_to @handbook, notice: 'Handbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @handbook }
      else
        format.html { render :edit }
        format.json { render json: @handbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handbooks/1
  # DELETE /handbooks/1.json
  def destroy
    @handbook.destroy
    respond_to do |format|
      format.html { redirect_to handbooks_url, notice: 'Handbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handbook
      @handbook = Handbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handbook_params
      params.require(:handbook).permit(:title, :description, :icon_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all

  end

  def show
     @user = User.find(params[:id])
  end
end

app/controllers/worships_controller.rb
class WorshipsController < ApplicationController
  before_action :set_worship, only: [:show, :edit, :update, :destroy]

  # GET /worships
  # GET /worships.json
  def index
    @worships = Worship.all
  end

  # GET /worships/1
  # GET /worships/1.json
  def show
    @worships = Worship.find(params[:id])

    @pin_worship = PinWorship.new

  end

  # GET /worships/new
  def new
    @worship = Worship.new
  end

  # GET /worships/1/edit
  def edit
  end

  # POST /worships
  # POST /worships.json
  def create
    @worship = Worship.new(worship_params)

    respond_to do |format|
      if @worship.save
        format.html { redirect_to @worship, notice: 'Worship was successfully created.' }
        format.json { render :show, status: :created, location: @worship }
      else
        format.html { render :new }
        format.json { render json: @worship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worships/1
  # PATCH/PUT /worships/1.json
  def update
    respond_to do |format|
      if @worship.update(worship_params)
        format.html { redirect_to @worship, notice: 'Worship was successfully updated.' }
        format.json { render :show, status: :ok, location: @worship }
      else
        format.html { render :edit }
        format.json { render json: @worship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worships/1
  # DELETE /worships/1.json
  def destroy
    @worship.destroy
    respond_to do |format|
      format.html { redirect_to worships_url, notice: 'Worship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worship
      @worship = Worship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worship_params
      params.require(:worship).permit(:days)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/handbooks_helper.rb
module HandbooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pin_worships_helper.rb
module PinWorshipsHelper
end

app/helpers/pinpin_pin_worshops_helper.rb
module PinpinPinWorshopsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/worships_helper.rb
module WorshipsHelper
end

app/views/handbooks/_form.html.erb
<%= form_with(model: handbook, local: true) do |form| %>
  <% if handbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(handbook.errors.count, "error") %> prohibited this handbook from being saved:</h2>

      <ul>
      <% handbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :handbook_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :handbook_description %>
  </div>

  <div class="field">
    <%= form.label :icon_url %>
    <%= form.text_field :icon_url, id: :handbook_icon_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/handbooks/edit.html.erb
<h1>Editing Handbook</h1>

<%= render 'form', handbook: @handbook %>

<%= link_to 'Show', @handbook %> |
<%= link_to 'Back', handbooks_path %>

app/views/handbooks/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Handbooks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Icon url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handbooks.each do |handbook| %>
      <tr>
        <td><%= handbook.title %></td>
        <td><%= handbook.description %></td>
        <td><%= handbook.icon_url %></td>
        <td><%= link_to 'Show', handbook %></td>
        <td><%= link_to 'Edit', edit_handbook_path(handbook) %></td>
        <td><%= link_to 'Destroy', handbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Handbook', new_handbook_path %>

 -->

<!-- start our section -->
<section class="follow">
    <div class="container">
      <p id="notice"><%= notice %></p>

      <h1>Hand Book</h1>

      <% @handbooks.each do |handbook| %>
        <div class="main-law">
            <h1>  <%= handbook.title %></h1>
            <p><%= handbook.description %></p>


            <%= link_to 'See More', handbook , class: 'btn btn-danger' %>
        </div>
        <% end %>

    </div>

</section>



<!-- end our section -->

app/views/handbooks/new.html.erb
<h1>New Handbook</h1>

<%= render 'form', handbook: @handbook %>

<%= link_to 'Back', handbooks_path %>

app/views/handbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @handbook.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @handbook.description %>
</p>

<p>
  <strong>Icon url:</strong>
  <%= @handbook.icon_url %>
</p>

<%= link_to 'Edit', edit_handbook_path(@handbook) %> |
<%= link_to 'Back', handbooks_path %>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :note_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.text %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/worships/_form.html.erb
<%= form_with(model: worship, local: true) do |form| %>
  <% if worship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worship.errors.count, "error") %> prohibited this worship from being saved:</h2>

      <ul>
      <% worship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :days %>
    <%= form.text_field :days, id: :worship_days %>
  </div>


    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/worships/_pin.html.erb
<%= form_for([@worship, @worship.pin_worship.build], :method => puts, remote: true) do |f| %>
    <%= f.text_area :title, label: "Reply to thread" %>
    <%= f.button :submit, class: "button" %>
<% end %>

<%= form_with([@worship, @worship.pin_worship.build], :method => puts, remote: true) do |form| %>
    <% if pin_worship.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(pin_worship.errors.count, "error") %> prohibited this pin_worship from being saved:</h2>

          <ul>
            <% pin_worship.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :pin_worship_title %>
    </div>

    <div class="field">
      <%= form.label :lat %>
      <%= form.text_field :lat, id: :pin_worship_lat %>
    </div>

    <div class="field">
      <%= form.label :lng %>
      <%= form.text_field :lng, id: :pin_worship_lng %>
    </div>

    <div class="field">
      <%= form.label :img_url %>
      <%= form.text_field :img_url, id: :pin_worship_img_url %>
    </div>

    <div class="field">
      <%= form.label :info_text %>
      <%= form.text_field :info_text, id: :pin_worship_info_text %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/worships/edit.html.erb
<h1>Editing Worship</h1>

<%= render 'form', worship: @worship %>

<%= link_to 'Show', @worship %> |
<%= link_to 'Back', worships_path %>

app/views/worships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Worships</h1>

<table>
  <thead>
    <tr>
      <th>Days</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @worships.each do |worship| %>
      <tr>
        <td><%= worship.days %></td>
        <td><%= link_to 'Show', worship %></td>
        <td><%= link_to 'Edit', edit_worship_path(worship) %></td>
        <td><%= link_to 'Destroy', worship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worship', new_worship_path %>

app/views/worships/new.html.erb
<h1>New Worship</h1>

<%= render 'form', worship: @worship %>

<%= link_to 'Back', worships_path %>

app/views/worships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Days:</strong>
  <%= @worship.days %>
</p>



<%= link_to 'Back', worships_path %>